### ISSUE TITLE
@codebase says "Error getting context items from codebase: Error: no available backend found. ERR:"

### ISSUE THREAD

**Issue by TyDunn** [continuedev/continue#1070]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://continue.dev/docs/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: MacOS
- Continue: Latest (Pre-release)
- IDE: VS Code
```

### Description

I am unable to use `@codebase` to ask questions of my codebase right now

### To reproduce

1. Open VS Code with a project
2. Type `@codebase` and then ask a question
3. See that it says "Error getting context items from codebase: Error: no available backend found. ERR:"

### Log output

```Shell
Error getting context items from codebase: Error: no available backend found. ERR:
```

**Comment by sestinj** [comment]
Solved with https://github.com/continuedev/continue/commit/c482b6ba0d0ce11ef48bc2b116bd1635ce5adad1

Caused by https://github.com/continuedev/continue/commit/189302be5fa2748d246288c4b6f27d47a551152f

**Comment by helena75** [comment]
Seems like the error still persists. 

`Error getting context items from codebase: Error: no available backend found. ERR:`

- OS: Windows
- Continue: Latest (Pre-release)
- IDE: VS Code

**Comment by Niqnil** [comment]
I got the error too. Not sure if related to my other issue https://github.com/continuedev/continue/issues/1043.

- OS: Ubuntu 22.04.4
- Continue: v0.8.23
- IDE: vscode

Logs:
```
Error loading submenu items from folder: RangeError: path should be a `path.relative()`d string, but got "..."
c @ notificationsAlerts.ts:42
notificationsAlerts.ts:42 Error loading submenu items from file: RangeError: path should be a `path.relative()`d string, but got "..."
c @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] rejected promise not handled within 1 second: RangeError: path should be a `path.relative()`d string, but got "..."
w @ console.ts:137
console.ts:137 [Extension Host] stack trace: RangeError: path should be a `path.relative()`d string, but got "..."
    at throwError (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328458:13)
    at checkPath (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328472:16)
    at Ignore._test (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328560:9)
    at Ignore.ignores (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328587:21)
    at traverseDirectory (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329337:32)
    at traverseDirectory (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329399:24)
    at traverseDirectory (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329399:24)
    at traverseDirectory (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329399:24)
    at _VsCodeIdeUtils.getDirectoryContents (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329619:26)
    at VsCodeIde.listWorkspaceContents (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329962:18)
    at VsCodeIde.getStats (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329923:23)
    at CodebaseIndexer.refresh (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:187947:25)
    at _VsCodeExtension.refreshCodebaseIndex (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:330910:26)
w @ console.ts:137
mainThreadExtensionService.ts:81 [Continue.continue]path should be a `path.relative()`d string, but got "..."
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 RangeError: path should be a `path.relative()`d string, but got "..."
    at throwError (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328458:13)
    at checkPath (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328472:16)
    at Ignore._test (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328560:9)
    at Ignore.ignores (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:328587:21)
    at traverseDirectory (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329337:32)
    at traverseDirectory (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329399:24)
    at traverseDirectory (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329399:24)
    at traverseDirectory (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329399:24)
    at _VsCodeIdeUtils.getDirectoryContents (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329619:26)
    at VsCodeIde.listWorkspaceContents (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329962:18)
    at VsCodeIde.getStats (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:329923:23)
    at CodebaseIndexer.refresh (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:187947:25)
    at _VsCodeExtension.refreshCodebaseIndex (vscode-file://vscode-app/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:330910:26)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
console.ts:137 [Extension Host] [vscode-icons] v12.7.0 activated!
log.ts:439   ERR Unknown (FileSystemError): Failed to move 'runtime_2024-04-11_10-03-25_137864.log' to the trash (Failed to move item to trash)
    at u.create (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:56:3442)
    at b (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:56:3560)
    at y (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:61:40116)
log.ts:439   ERR Failed to move 'runtime_2024-04-11_10-03-25_137864.log' to the trash (Failed to move item to trash): Unknown (FileSystemError): Failed to move 'runtime_2024-04-11_10-03-25_137864.log' to the trash (Failed to move item to trash)
    at u.create (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:56:3442)
    at b (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:56:3560)
    at y (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:61:40116)
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is unresponsive.
localProcessExtensionHost.ts:273 Extension Host
localProcessExtensionHost.ts:274 Debugger attached.
log.ts:419  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is responsive.
log.ts:419  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
log.ts:429  WARN UNRESPONSIVE extension host: 'continue.continue' took 69.9975474725697% of 3507.687ms, saved PROFILE here: 'file:///tmp/exthost-b80c4d.cpuprofile'
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is unresponsive.
localProcessExtensionHost.ts:273 Extension Host
localProcessExtensionHost.ts:274 Debugger attached.
log.ts:419  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is responsive.
log.ts:419  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
log.ts:429  WARN UNRESPONSIVE extension host: 'continue.continue' took 73.34148001598379% of 3000.873ms, saved PROFILE here: 'file:///tmp/exthost-2ca02d.cpuprofile'
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is unresponsive.
localProcessExtensionHost.ts:273 Extension Host
localProcessExtensionHost.ts:274 Debugger attached.
log.ts:419  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is responsive.
log.ts:419  INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session
log.ts:429  WARN UNRESPONSIVE extension host: 'continue.continue' took 72.00801899721505% of 3404.735ms, saved PROFILE here: 'file:///tmp/exthost-e99d16.cpuprofile'
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is unresponsive.
localProcessExtensionHost.ts:273 Extension Host
localProcessExtensionHost.ts:274 Debugger attached.
log.ts:419  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:429  WARN UNRESPONSIVE extension host: 'continue.continue' took 77.57630280021831% of 3880.452ms, saved PROFILE here: 'file:///tmp/exthost-606b93.cpuprofile'
log.ts:419  INFO Extension host (LocalProcess pid: 12235) is responsive.
console.ts:137 [Extension Host] TypeError: binding_1.binding.InferenceSession is not a constructor
    at new OnnxruntimeSessionHandler (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:89064:84)
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:89101:23
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
w @ console.ts:137
console.ts:137 [Extension Host] Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback. 
w @ console.ts:137
mainThreadExtensionService.ts:81 [Continue.continue]no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:88941:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.create (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:88922:108)
    at constructSession (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:106165:12)
    at async Promise.all (index 1)
    at Function.from_pretrained (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:106577:19)
    at Function.from_pretrained (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:109020:18)
    at async Promise.all (index 1)
    at loadItems (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:116345:3)
    at pipeline2 (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:116305:19)
    at Function.getInstance (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:117781:27)
    at _TransformersJsEmbeddingsProvider.embed (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:117795:25)
    at indexDocs (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:326530:31)
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:327031:32
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
localProcessExtensionHost.ts:273 Extension Host
localProcessExtensionHost.ts:274 Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm')failed to asynchronously prepare wasm: RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.Aborted(RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
w @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:88941:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.create (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:88922:108)
    at constructSession (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:106165:12)
    at async Promise.all (index 1)
    at Function.from_pretrained (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:106577:19)
    at Function.from_pretrained (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:109020:18)
    at async Promise.all (index 1)
    at loadItems (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:116345:3)
    at pipeline2 (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:116305:19)
    at Function.getInstance (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:117781:27)
    at _TransformersJsEmbeddingsProvider.embed (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:117795:25)
    at indexDocs (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:326530:31)
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:327031:32
w @ console.ts:137
mainThreadExtensionService.ts:81 [Continue.continue]no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
mainThreadExtensionService.ts:82 Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(Error: ENOENT: no such file or directory, open '/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/dist/ort-wasm-simd-threaded.wasm'). Build with -sASSERTIONS for more info.
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:88941:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.create (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:88922:108)
    at constructSession (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:106165:12)
    at async Promise.all (index 1)
    at Function.from_pretrained (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:106577:19)
    at Function.from_pretrained (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:109020:18)
    at async Promise.all (index 1)
    at loadItems (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:116345:3)
    at pipeline2 (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:116305:19)
    at Function.getInstance (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:117781:27)
    at _TransformersJsEmbeddingsProvider.embed (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:117795:25)
    at indexDocs (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:326530:31)
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:327031:32
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
console.ts:137 [Extension Host] TypeError: binding_1.binding.InferenceSession is not a constructor
    at new OnnxruntimeSessionHandler (/home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:89064:84)
    at /home/user/.vscode/extensions/continue.continue-0.8.23-linux-x64/out/extension.js:89101:23
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
w @ console.ts:137
console.ts:137 [Extension Host] Something went wrong during model construction (most likely a missing operation). Using `wasm` as a fallback. 
w @ console.ts:137
notificationsAlerts.ts:42 Error getting context items from docs: Error: no available backend found. ERR:
c @ notificationsAlerts.ts:42
```
