### ISSUE TITLE
Issues with AzureAI / o1 following 0.8.63 release

### ISSUE THREAD

**Issue by Patrick-Erichsen** [continuedev/continue#3477]
## Overview
https://github.com/continuedev/continue/issues/3427#issuecomment-2548665948 seems like the most likely potential root cause:

>  v0.8.63 seems to have re-introduced URL construction errors for Azure OpenAI endpoints.

## Related issues
- https://github.com/continuedev/continue/issues/3407
- https://github.com/continuedev/continue/issues/3424
- https://github.com/continuedev/continue/issues/3388
- https://github.com/continuedev/continue/issues/3427

**Comment by sestinj** [comment]
I just released v0.8.66-vscode with a hot fix to solve all of the Azure problems

https://github.com/continuedev/continue/releases/tag/v0.8.66-vscode

**Comment by thomaspmorgan** [comment]
@sestinj , tried v0.8.66 and still see the 404 error

**Comment by DaCostaMathias** [comment]
@sestinj, I also try v0.8.66 and latest pre release but I still have the issue.
![12-31-2024 (10-43-25)](https://github.com/user-attachments/assets/cff27b50-3f04-4219-8bed-d33349ed3e99)

Could it be link to the path issue reading the config file that is currently affecting JetBrains version of the plugin?

**Comment by Patrick-Erichsen** [comment]
cc @sestinj here

@DaCostaMathias I don't think this is related to the path URI issues based on the 404 that @eweidner is getting.

**Comment by ntaylor-ads** [comment]
I updated the config for my models to use "azure" as the provider. (I had previously changed it back to openai because of #2830). Now all chat models are working. However, (like @DaCostaMathias) the text-embedding-3-large model is not working with either provider.

With azure as the provider:
```
Error: Failed to generate embeddings for 8 chunks with provider: undefined: TypeError: this.embeddingsProvider.embed is not a function
```
With openai as the provider:
```
Error: Failed to generate embeddings for 10 chunks with provider: OpenAI2::text-embedding-3-large::500: Error: 404 Resource not found
```
Remaining issues seem related to #3072

**Comment by ntaylor-ads** [comment]
Update: specifying api version "2024-02-15-preview" for the embeddings got it working for me
```json
{
    "provider": "openai",
    "model": "text-embedding-3-large",
    "apiType": "azure",
    "deployment": "text-embedding-3-large",
    "apiBase": "https://<REDACTED>.openai.azure.com/",
    "apiKey": <REDACTED>,
    "apiVersion": "2024-02-15-preview"
  }
```

**Comment by eweidner** [comment]
@ntaylor-ads You solved my problem! I have had provider=openai for my azure gpt endpoints forever (and still working that way in v 0.8.61). I missed the move to use an "azure" provider.

Now I have these settings and it's working in the 0.8.66 release

```
      "provider": "azure",
      "model": "gpt-4",
      "apiType": "azure",
      "engine": "gpt-4o-240806-model",
      "deployment": "gpt-4o-240806-model",
      "apiVersion": "2024-08-01-preview"
       ...other values clipped...
```

I had to add `deployment` a few months ago, but today all I changed was the provider.
