### ISSUE TITLE
issues.data.map is not a function

### ISSUE THREAD

**Issue by Cheizr** [continuedev/continue#3027]
### Before submitting your bug report

- [ ] I believe this is a bug. I'll try to join the [Continue Discord](https://discord.gg/NWtdYexhMs) for questions
- [ ] I'm not able to find an [open issue](https://github.com/continuedev/continue/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://docs.continue.dev/troubleshooting) on the Continue Docs

### Relevant environment info

```Markdown
- OS: w10
- Continue version: v0.8.57
- IDE version: 1.95.3
- Model:
- config.json:
  
{
  "models": [
    {
      "title": "Llama 3.1 8B",
      "provider": "ollama",
      "model": "llama3.1:8b"
    },
    {
      "model": "AUTODETECT",
      "title": "Ollama",
      "completionOptions": {
        "temperature": 1
      },
      "apiBase": "http://localhost:11434/v1/",
      "provider": "ollama"
    },
    {
      "model": "AUTODETECT",
      "title": "LM Studio",
      "apiBase": "http://localhost:1234/v1/",
      "provider": "lmstudio"
    }
  ],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "Qwen2.5-Coder 1.5B",
    "provider": "ollama",
    "model": "qwen2.5-coder:1.5b"
  },
  "tabAutocompleteOptions": {
    "debounceDelay": 0
  },
  "embeddingsProvider": {
    "provider": "ollama",
    "model": "nomic-embed-text"
  },
  "contextProviders": [
    {
      "name": "url"
    },
    {
      "name": "codebase",
      "params": {
        "nRetrieve": 45,
        "nFinal": 15,
        "useReranking": true
      }
    },
    {
      "name": "docs"
    },
    {
      "name": "folder"
    },
    {
      "name": "diff"
    },
    {
      "name": "code"
    },
    {
      "name": "terminal"
    },
    {
      "name": "open",
      "params": {
        "onlyPinned": false
      }
    },
    {
      "name": "issue",
      "params": {
        "repos": [
          {
            "owner": "continuedev",
            "repo": "continue"
          }
        ],
        "githubToken": "xxx"
      }
    }
  ],
  "allowAnonymousTelemetry": false,
  "docs": [
    {
      "title": "React",
      "startUrl": "https://react.dev/reference/"
    }
  ]
}
```

### Description

After updating continue to 0.9.4 when i open VSCode the following error is displayed: issues.data.map is not a function

### Log output

```Shell
[Extension Host] Error handling webview message: {
  "msg": {
    "messageId": "50144d10-a9df-4df5-86d2-469097f0a639",
    "messageType": "context/loadSubmenuItems",
    "data": {
      "title": "issue"
    }
  }
}

TypeError: issues.data.map is not a function
uGi @ console.ts:137
notificationsAlerts.ts:42 issues.data.map is not a function
c @ notificationsAlerts.ts:42
index.js:747 Error loading items for issue: Object
```

**Comment by Patrick-Erichsen** [comment]
Problematic code line appears to be here: [...issues.data.map((issue) => ({](https://github.com/continuedev/continue/blob/ab1ad0ae48eeceee87043cae9a7862a1c4f70da0/core/context/providers/GitHubIssuesContextProvider.ts#L88-L89)

If you're not actively using the Issues context provider you can just remove that from your config.json. If you are using it, can you verify that the GitHub token you're using is still valid?
